= tutorial
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font

== Overview
The purpose of this repository is to illustrate main features and functionality offered by the OSGi framework and its Apache Felix implementation. The repository contains codebase developed according to the Apache Felix OSGi Tutorial published at https://felix.apache.org/documentation/tutorials-examples-and-presentations/apache-felix-osgi-tutorial.html.

The repository consists of nine examples which constitute a single and simple dictionary application. Each example represents a separate part (OSGi bundle) of the application. Exceptions are examples #8 and #9, which aren't supposed to be compiled, built or used.   

== Deployment
[upperalpha]
. The commands pertaining to the deployment should be run from the root level of the project.
. It is assumed, that the full path to the repository is `/home/herman_ciechanowiec/0_prog/osgi_first_steps`. If that is not the case, the commands pertaining to the deployment should be changed respectively.
. To deploy the application, run all the commands given below sequentially, starting from the first one.

=== Apache Felix Instance
Start the Apache Felix instance. This will start an Apache Felix console. The command starting the instance should be run in a separate terminal window, since compile and build commands listed in next sections should be run in a usual console, i.e. no in the Apache Felix console:

    cd felix_instance && java -jar bin/felix.jar

=== Example 1
To compile:

    javac -cp felix.jar -d ./classes/example1 ./classes/example1/*.java

To pack into jar:

    jar cfm jars/example1.jar manifests/example1/manifest.mf -C classes/example1/ tutorial/example1/

Start the bundle running the following command inside the Apache Felix console:

    start file:/home/herman_ciechanowiec/0_prog/osgi_first_steps/jars/example1.jar

=== Example 2
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

javac -cp felix.jar -d ./classes/example2 ./classes/example2/*.java

=== Example 2b
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example2b ./classes/example2b/*.java

=== Example 3
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example3 ./classes/example3/*.java

=== Example 4
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example4 ./classes/example4/*.java

=== Example 5
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example5 ./classes/example5/*.java

=== Example 6
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example6 ./classes/example6/*.java

=== Example 7
As for Example 1, but:
[upperalpha]
. change the number of the example
. to compile use:

    javac -cp felix.jar:jars/example6.jar -d ./classes/example7 ./classes/example7/*.java

=== Example 8
The example 8 was supposed to serve as a demonstration of Service Binder (org.apache.felix.servicebinder) functionalities. However, the Service Binder has been removed from the Apache Felix, so it wasn't implemented in this repository.

=== Example 9

The purpose of the example 9 is just to present another way of `SpellCheck` implementation. It isn't supposed to be compiled and run.
