= tutorial
:reproducible:
:doctype: article
:author: Herman Ciechanowiec
:email: herman@ciechanowiec.eu
:chapter-signifier:
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:toc: left
:toclevels: 5
:icons: font

== On Running Commands
The commands given below must be run from the root level of the project.

== Example 1
To compile:

    javac -cp felix.jar -d ./classes/example1 ./classes/example1/*.java

To pack into jar:

    jar cfm jars/example1.jar manifests/example1/manifest.mf -C classes/example1/ tutorial/example1/

Start the Apache Felix instance:

    java -jar felix.jar

Inside the Apache Felix console start the bundle:

    start file:/home/herman_ciechanowiec/0_prog/tutorial/jars/example1.jar

== Example 2
As for Example 1, but change the number of the example

== Example 2b
As for Example 1, but:

* change the number of the example
* to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example2b ./classes/example2b/*.java

== Example 3
As for Example 1, but:

* change the number of the example
* to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example3 ./classes/example3/*.java

== Example 4
As for Example 1, but:

* change the number of the example
* to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example4 ./classes/example4/*.java

== Example 5
As for Example 1, but:

* change the number of the example
* to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example5 ./classes/example5/*.java

== Example 6
As for Example 1, but:

* change the number of the example
* to compile use:

    javac -cp felix.jar:jars/example2.jar -d ./classes/example6 ./classes/example6/*.java
